name: tech_with_tim
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  
  fluttertoast: ^8.0.9

  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0




flutter:

 
  uses-material-design: true

  assets:
    - images/syamim.png
    - images/syamim2.jpeg
    - images/tmf.png
    - images/uitm.png
    - images/smj.png
    - images/laptop.jpeg
    - images/wordpress.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf